# Generated by Django 3.0.3 on 2022-04-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taipei_restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_number', models.IntegerField()),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_rating', models.CharField(max_length=100)),
                ('restaurant_address', models.CharField(max_length=100)),
                ('restaurant_type', models.CharField(max_length=100)),
            ],
        ),
    ]
